# Generated by Django 3.0.6 on 2021-07-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='image',
            field=models.FileField(null=True, upload_to='user_images'),
        ),
    ]
